### PR TITLE
Support wagtail 4.1 & Django 4.1

### PR DESCRIPTION
**Pull request by nickmoreton**
This upgrades the package to use up to Wagtail 4.1 and Django 4.1

It drops support for Wagtail < 2.15 and Django < 3.2

### CODE REVIEW

**Review by victoriachan — CHANGES_REQUESTED** [review]
I can't get the sandbox to work. The requirements.txt on the sandbox says:

```
Django>=2.2,<2.3
wagtail>=2.6,<2.7
```

The documentation such as Readme.rst and Installation.rst, would need updating too, as they currently say "Wagtail Personalisation requires Wagtail 2.0 or 2.1 and Django 1.11 or 2.0.".

They needs to be updated to match the current supported versions?

**Comment by easherma-truth** [comment]
How does this relate to https://github.com/wagtail/wagtail-personalisation/pull/243 ?

**Comment by nickmoreton** [comment]
> I can't get the sandbox to work. The requirements.txt on the sandbox says:
> 
> ```
> Django>=2.2,<2.3
> wagtail>=2.6,<2.7
> ```
> 
> The documentation such as Readme.rst and Installation.rst, would need updating too, as they currently say "Wagtail Personalisation requires Wagtail 2.0 or 2.1 and Django 1.11 or 2.0.".
> 
> They needs to be updated to match the current supported versions?

@victoriachan I have update the sandbox and it's now working OK for me too. I also adjusted the supported wagtail and django versions in the docs.

**Comment by nickmoreton** [comment]
> How does this relate to #243 ?

@easherma-truth Thanks for asking. That PR had work this was built off. It has been closed and those changes are part of this work now.

**Comment by zerolab** [comment]
Closing in favour of #251

**Pull request closed without merging**
